### ISSUE TITLE
Server Crash - EntityMobLouse

### ISSUE THREAD

**Issue by Redlotus99** [chylex/Hardcore-Ender-Expansion#100]
My server started crashing recently and will not restart. It seems to be something with the Louse Mob.

Here is a copy of the error I'm seeing.

Time: 2/13/15 2:57 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.entity.EntityLiving.func_70623_bb(EntityLiving.java:546)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:606)
	at net.minecraft.entity.EntityCreature.func_70626_be(EntityCreature.java:221)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2047)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:388)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:36)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1874)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:213)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:41)
	at chylex.hee.entity.mob.EntityMobLouse.func_70071_h_(EntityMobLouse.java:94)
	at net.minecraft.world.World.func_72866_a(World.java:2647)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
	at net.minecraft.world.World.func_72870_g(World.java:2600)
	at net.minecraft.world.World.func_72939_s(World.java:2412)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Unknown Source)

**Comment by chylex** [comment]
Need -full- crash report.

**Comment by Redlotus99** [comment]
Sorry for the delay.

http://pastebin.com/i8s9Pgnh

**Comment by chylex** [comment]
Cauldron is not supported. Backup the world and replicate the issue with only Forge and HEE installed, if it still crashes then reopen the issue. The crash doesn't originate from HEE code, otherwise the line that mentions it would be on top of the report.

**Comment by Redlotus99** [comment]
No worries. I figured I'd get Cauldron was the cause.

**Comment by chylex** [comment]
It's either cauldron or one of the coremods.
