### ISSUE TITLE
[INVALID] Monster Spawner issues

### ISSUE THREAD

**Issue by cristianmartin** [chylex/Hardcore-Ender-Expansion#131]
Hello, I am playing HorizonsII and whenever I try to collect the monster spawners and place them in my base, they don't work. In addition, if I try with a spawner collector (from EC3) I get this error:

Unexpected error

java.lang.ClassCastException: chylex.hee.tileentity.TileEntityCustomSpawner cannot be cast to net.minecraft.tileentity.TileEntityMobSpawner
at ec3.common.item.ItemSpawnerCollector.onItemUseFirst(ItemSpawnerCollector.java:32)
at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:317)
at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by chylex** [comment]
EC3 isn't checking the tile entity type. HEE spawners don't extend the vanilla TE.
