### ISSUE TITLE
[FIXED 1.8.4] Crash on server with debug mode enabled

### ISSUE THREAD

**Issue by spamenigma** [chylex/Hardcore-Ender-Expansion#141]
After doing a lot of mod updates I had some crashing issues and have spent time narrowing it down to a selective set of mods.

AncientTrees-1.7.10-1.6.2.jar
extrautilities-1.2.11.jar
forestry_1.7.10-3.6.4.22.jar
HardcoreEnderExpansion  MC-1.7.10  v1.8.3.jar

If all three of those other mods are on then it appears HEE crashes with the following crash report, if I disable any one of those it loads.

Hope you can advise? :)

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 09/09/15 16:38
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at chylex.hee.proxy.NotificationCommonProxy.tryDeliverNotifications(NotificationCommonProxy.java:50)
	at chylex.hee.proxy.NotificationCommonProxy.report(NotificationCommonProxy.java:31)
	at chylex.hee.system.logging.Log.warn(Log.java:73)
	at chylex.hee.mechanics.misc.StardustDecomposition.addFromString(StardustDecomposition.java:122)
	at chylex.hee.system.ConfigHandler.loadGeneralConfig(ConfigHandler.java:118)
	at chylex.hee.system.ConfigHandler.loadGeneral(ConfigHandler.java:41)
	at chylex.hee.proxy.ModCommonProxy.loadConfiguration(ModCommonProxy.java:12)
	at chylex.hee.HardcoreEnderExpansion.onPreInit(HardcoreEnderExpansion.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 3.19.0-21-generic
	Java Version: 1.7.0_79, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1404467008 bytes (1339 MB) / 2077753344 bytes (1981 MB) up to 3151495168 bytes (3005 MB)
	JVM Flags: 5 total; -Xms2048m -Xmx3072m -XX:PermSize=256m -XX:+UseParNewGC -XX:+UseConcMarkSweepGC
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1492-1.7.10-universal.jar) 
	UCH	Forge{10.13.4.1492} [Minecraft Forge] (forge-1.7.10-10.13.4.1492-1.7.10-universal.jar) 
	UCE	HardcoreEnderExpansion{1.8.3} [Hardcore Ender Expansion] (HardcoreEnderExpansion  MC-1.7.10  v1.8.3.jar) 
	UCH	Forestry{3.6.4.22} [Forestry for Minecraft] (forestry_1.7.10-3.6.4.22.jar) 
	UCH	koresample{1.7.10-1.3.2} [Kore Sample] (KoreSample-1.7.10-1.3.2.jar) 
	UCH	dendrology{1.7.10-1.6.2} [Ancient Trees] (AncientTrees-1.7.10-1.6.2.jar) 
	UCH	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCH	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCH	ExtraUtilities{1.2.11} [Extra Utilities] (extrautilities-1.2.11.jar) 
	UCH	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCH	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCH	MCFrames{1.0} [MCFrames] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCH	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
	UCH	MrTJPCoreMod{1.1.0.31} [MrTJPCore] (MrTJPCore-1.1.0.31-universal.jar) 
	UCH	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by chylex** [comment]
Hmm... which of these mods are coremods?

**Comment by chylex** [comment]
I would suggest not using the stardust decomposition config and using the config API instead, but it won't solve the underlying issue. I would understand if it happened without any other mods (because the code for reporting warnings doesn't seem to be perfectly safe), but right now it looks like some coremod is breaking things or causing HEE to be called too early, so not quite sure.

**Comment by chylex** [comment]
Actually, this should never happen unless you have debugging enabled. Check your config.

**Comment by spamenigma** [comment]
Hah, yes that was it! debugging was on for some reason (Can only assume it was a default of a previous version?). Thanks for responding and helping!

**Comment by chylex** [comment]
It's never enabled by default, it has a massive performance impact. I'll leave this open because I still need to fix the crash, I never tested debugging in multiplayer.

**Comment by spamenigma** [comment]
Odd, as I'm as sure as I can be I didn't enable it, so just assumed it may have been from a previous version that accidentally had it on.. (I've been regularly updating my pack for the best part of a year).

I know there are more mods that can trigger this error than just the 3 i mentioned, I had one of them disabled when I put all my others back and the issue still occurred. This was the error I got before turning off debug: http://pastebin.com/1Fkbj2jg

**Comment by chylex** [comment]
You should check the logs, it means you have warnings there (in this case it's a config setting that will stop working soon). Debug mode prints all this stuff directly in your chat, so I would definitely not suggest keeping it enabled :P.

**Comment by chylex** [comment]
Fixed in upcoming update.
