### ISSUE TITLE
overrideRemoveBrokenRecipes report

### ISSUE THREAD

**Issue by iamfletch** [chylex/Hardcore-Ender-Expansion#156]
---- Minecraft Crash Report ----
// You're mean.

Time: 12/12/15 18:38
Description: Initializing game

java.lang.RuntimeException: A defective recipe has crashed the game! Another mod is creating recipes with non-existent blocks or items, which is a serious error that will cause item or even world loss when crafting these recipes. Corrupted recipes have been saved in the log with tag [HEE-ORB], please try to find which mod they belong to and report them to the respective modder. Then enable the 'overrideRemoveBrokenRecipes' option in Hardcore Ender Expansion and the game will start.
	at net.minecraft.item.ItemStack.func_77984_f(ItemStack.java:197)
	at net.minecraft.item.ItemStack.func_77951_h(ItemStack.java:207)
	at chylex.hee.mechanics.orb.OrbAcquirableItems.addItemToList(OrbAcquirableItems.java:156)
	at chylex.hee.mechanics.orb.OrbAcquirableItems.initialize(OrbAcquirableItems.java:72)
	at chylex.hee.HardcoreEnderExpansion.onPostInit(HardcoreEnderExpansion.java:168)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.item.ItemStack.func_77984_f(ItemStack.java:197)
	at net.minecraft.item.ItemStack.func_77951_h(ItemStack.java:207)
	at chylex.hee.mechanics.orb.OrbAcquirableItems.addItemToList(OrbAcquirableItems.java:156)
	at chylex.hee.mechanics.orb.OrbAcquirableItems.initialize(OrbAcquirableItems.java:72)
	at chylex.hee.HardcoreEnderExpansion.onPostInit(HardcoreEnderExpansion.java:168)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.7.0_79, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 588311632 bytes (561 MB) / 1398800384 bytes (1334 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -XX:MaxPermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 82 mods loaded, 82 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{7.10.99.99} [Forge Mod Loader] (modpack.jar) 
	UCHIJ	Forge{10.13.4.1558} [Minecraft Forge] (modpack.jar) 
	UCHIJ	AM2-Preloader{0.0.2} [AMCore] (minecraft.jar) 
	UCHIJ	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJ	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJ	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJ	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHIJ	voltzenginepreloader{0.0.1} [Voltz Engine Preloader] (minecraft.jar) 
	UCHIJ	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJ	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHIJ	arsmagica2{1.4.0.008} [Ars Magica 2] (1.7.10_AM2-1.4.0.008.jar) 
	UCHIJ	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJ	BuildCraft|Core{7.1.14} [BuildCraft] (buildcraft-7.1.14.jar) 
	UCHIJ	BuildCraft|Builders{7.1.14} [BC Builders] (buildcraft-7.1.14.jar) 
	UCHIJ	BuildCraft|Transport{7.1.14} [BC Transport] (buildcraft-7.1.14.jar) 
	UCHIJ	BuildCraft|Energy{7.1.14} [BC Energy] (buildcraft-7.1.14.jar) 
	UCHIJ	BuildCraft|Silicon{7.1.14} [BC Silicon] (buildcraft-7.1.14.jar) 
	UCHIJ	BuildCraft|Factory{7.1.14} [BC Factory] (buildcraft-7.1.14.jar) 
	UCHIJ	Additional-Buildcraft-Objects{MC1.7.10-BC7.1release4.0.6} [Additional Buildcraft Objects] (ABO-MC1.7.10-BC7.1release4.0.6.jar) 
	UCHIJ	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHIJ	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) 
	UCHIJ	bdlib{1.9.4.109} [BD Lib] (bdlib-1.9.4.109-mc1.7.10.jar) 
	UCHIJ	BiblioCraft{1.11.4} [BiblioCraft] (BiblioCraft[v1.11.4][MC1.7.10].jar) 
	UCHIJ	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCHIJ	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
	UCHIJ	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1067-universal.jar) 
	UCHIJ	BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition] (BiblioWoods[BiomesOPlenty][v1.9].jar) 
	UCHIJ	ExtrabiomesXL{3.16.3} [ExtrabiomesXL] (extrabiomesxl_1.7.10-3.16.3.jar) 
	UCHIJ	BiblioWoodsEBXL{1.4} [BiblioWoods ExtraBiomesXL Edition] (BiblioWoods[ExtraBiomesXL][v1.4].jar) 
	UCHIE	HardcoreEnderExpansion{1.8.4} [Hardcore Ender Expansion] (HardcoreEnderExpansion  MC-1.7.10  v1.8.4.jar) 
	UCHIJ	Forestry{4.2.1.48} [Forestry for Minecraft] (forestry_1.7.10-4.2.1.48.jar) 
	UCHIJ	BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition] (BiblioWoods[Forestry][v1.7].jar) 
	UCHIJ	BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition] (BiblioWoods[Natura][v1.5].jar) 
	UCHIJ	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	UCHIJ	BuildCraft|Robotics{7.1.14} [BC Robotics] (buildcraft-7.1.14.jar) 
	UCHIJ	CarpentersBlocks{3.3.7} [Carpenter's Blocks] (Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
	UCHIJ	chisel{2.5.1.44} [Chisel 2] (Chisel2-2.5.1.44.jar) 
	UCHIJ	chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.0.jar) 
	UCHIJ	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) 
	UCHIJ	darkcore{0.3} [Dark Core] (darkcore-0.3-45.jar) 
	UCHIJ	DynamicLights{1.3.9} [Dynamic Lights] (DynamicLights-1.7.10.jar) 
	UCHIJ	DynamicLights_onFire{1.0.5} [Dynamic Lights Burning Entity Module] (DynamicLights-1.7.10.jar) 
	UCHIJ	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.7.10.jar) 
	UCHIJ	DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module] (DynamicLights-1.7.10.jar) 
	UCHIJ	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJ	DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJ	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJ	DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light] (DynamicLights-1.7.10.jar) 
	UCHIJ	DynamicLights_otherPlayers{1.0.8} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJ	DynamicLights_thePlayer{1.1.4} [Dynamic Lights Player Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJ	EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar) 
	UCHIJ	EnderZoo{1.7.10-1.0.15.32} [Ender Zoo] (EnderZoo-1.7.10-1.0.15.32.jar) 
	UCHIJ	enhancedportals{3.0.12} [EnhancedPortals] (EnhancedPortals_1.7.10-universal-3.0.12.jar) 
	UCHIJ	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJ	extracells{2.3.3} [Extra Cells 2] (ExtraCells-1.7.10-2.3.3b162.jar) 
	UCHIJ	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCHIJ	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJ	ExtraTiC{1.4.5} [ExtraTiC] (ExtraTiC-1.7.10-1.4.5.jar) 
	UCHIJ	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.404.jar) 
	UCHIJ	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.404.jar) 
	UCHIJ	Growthcraft{2.1.0a} [Growthcraft] (growthcraft-core-1.7.10-2.1.0a.jar) 
	UCHIJ	Growthcraft|Cellar{2.1.0a} [Growthcraft Cellar] (growthcraft-cellar-1.7.10-2.1.0a.jar) 
	UCHIJ	Growthcraft|Apples{2.1.0} [Growthcraft Apples] (growthcraft-apples-1.7.10-2.1.0.jar) 
	UCHIJ	Growthcraft|Bamboo{2.1.0} [Growthcraft Bamboo] (growthcraft-bamboo-1.7.10-2.1.0.jar) 
	UCHIJ	Growthcraft|Grapes{2.1.0} [Growthcraft Grapes] (growthcraft-grapes-1.7.10-2.1.0.jar) 
	UCHIJ	Growthcraft|Hops{2.1.0} [Growthcraft Hops] (growthcraft-hops-1.7.10-2.1.0.jar) 
	UCHIJ	Growthcraft|Rice{2.1.0a} [Growthcraft Rice] (growthcraft-rice-1.7.10-2.1.0a.jar) 
	UCHIJ	VoltzEngine{0.7.2.188} [Voltz Engine] (VoltzEngine-1.7.10-0.7.2b188-dev-universal.jar) 
	UCHIJ	icbm{2.8.0.99} [ICBM] (ICBM-1.7.10-2.8.0b99-dev-universal.jar) 
	UCHIJ	NEIAddons{1.12.13.38} [NEI Addons] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJ	NEIAddons|Developer{1.12.13.38} [NEI Addons: Developer Tools] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJ	NEIAddons|AppEng{1.12.13.38} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJ	NEIAddons|Botany{1.12.13.38} [NEI Addons: Botany] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJ	NEIAddons|Forestry{1.12.13.38} [NEI Addons: Forestry] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJ	NEIAddons|CraftingTables{1.12.13.38} [NEI Addons: Crafting Tables] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJ	NEIAddons|ExNihilo{1.12.13.38} [NEI Addons: Ex Nihilo] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJ	neiintegration{1.1.0} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.0.jar) 
	UCHIJ	TardisMod{0.99} [Tardis Mod] (tardismod-1.7.10-0.99-207.jar) 
	UCHIJ	TMechworks{0.2.14.100} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.14.100.jar) 
	UCHIJ	WailaHarvestability{1.1.5} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.5.jar) 
	UCHIJ	XaeroMinimap{1.7.3.1} [Xaero's Minimap] (xaeros_minimap_v1.7.3.1_Forge_1.7.10.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 353.62' Renderer: 'GeForce GTX 560 Ti/PCIe/SSE2'
	CoFHCore: -[1.7.10]3.0.3-303
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	List of loaded APIs: 
		* appliedenergistics2|API (rv2) from appliedenergistics2-rv2-stable-10.jar
		* BiomesOPlentyAPI (1.0.0) from BiomesOPlenty-1.7.10-2.1.0.1067-universal.jar
		* BuildCraftAPI|blocks (1.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|blueprints (1.5) from buildcraft-7.1.14.jar
		* BuildCraftAPI|boards (2.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|core (1.0) from extrautilities-1.2.12.jar
		* BuildCraftAPI|crops (1.1) from buildcraft-7.1.14.jar
		* BuildCraftAPI|events (2.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|facades (1.1) from buildcraft-7.1.14.jar
		* BuildCraftAPI|filler (4.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|gates (4.1) from buildcraft-7.1.14.jar
		* BuildCraftAPI|items (1.1) from buildcraft-7.1.14.jar
		* BuildCraftAPI|library (2.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|lists (1.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|power (1.3) from buildcraft-7.1.14.jar
		* BuildCraftAPI|recipes (3.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|robotics (3.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|statements (1.1) from buildcraft-7.1.14.jar
		* BuildCraftAPI|tablet (1.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|tiles (1.2) from buildcraft-7.1.14.jar
		* BuildCraftAPI|tools (1.0) from VoltzEngine-1.7.10-0.7.2b188-dev-universal.jar
		* BuildCraftAPI|transport (4.1) from buildcraft-7.1.14.jar
		* CarpentersBlocks|API (3.3.7) from Carpenter's Blocks v3.3.7 - MC 1.7.10.jar
		* ChiselAPI (0.1.0) from Chisel2-2.5.1.44.jar
		* ChiselAPI|Carving (0.1.0) from Chisel2-2.5.1.44.jar
		* ChiselAPI|Rendering (0.1.0) from Chisel2-2.5.1.44.jar
		* CoFHAPI (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|block (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|core (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|energy (1.7.10R1.0.2) from forestry_1.7.10-4.2.1.48.jar
		* CoFHAPI|fluid (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|inventory (1.7.10R1.0.3) from EnderIO-1.7.10-2.2.8.381.jar
		* CoFHAPI|item (1.7.10R1.0.13B1) from extrautilities-1.2.12.jar
		* CoFHAPI|modhelpers (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|tileentity (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|transport (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|world (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|audio (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui|container (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui|element (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui|element|listbox (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui|slot (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|inventory (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|render (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|render|particle (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|util (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|util|helpers (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|util|position (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|world (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|world|feature (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.7.10-2.2.8.381.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.7.10-2.2.8.381.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.7.10-2.2.8.381.jar
		* ForestryAPI|apiculture (4.8.0) from forestry_1.7.10-4.2.1.48.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.7.10-4.2.1.48.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.7.10-4.2.1.48.jar
		* ForestryAPI|core (5.0.0) from forestry_1.7.10-4.2.1.48.jar
		* ForestryAPI|farming (2.1.0) from forestry_1.7.10-4.2.1.48.jar
		* ForestryAPI|food (1.1.0) from forestry_1.7.10-4.2.1.48.jar
		* ForestryAPI|fuels (2.0.1) from forestry_1.7.10-4.2.1.48.jar
		* ForestryAPI|genetics (4.7.0) from forestry_1.7.10-4.2.1.48.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.7.10-4.2.1.48.jar
		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.7.10-4.2.1.48.jar
		* ForestryAPI|mail (3.0.0) from forestry_1.7.10-4.2.1.48.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.7.10-4.2.1.48.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.7.10-4.2.1.48.jar
		* ForestryAPI|storage (3.0.0) from forestry_1.7.10-4.2.1.48.jar
		* ForestryAPI|world (2.1.0) from forestry_1.7.10-4.2.1.48.jar
		* Galacticraft API (1.0) from GalacticraftCore-1.7-3.0.12.404.jar
		* GrowthcraftAPI|Cellar (2.0) from growthcraft-cellar-1.7.10-2.1.0a.jar
		* GrowthcraftAPI|Core (2.0) from growthcraft-cellar-1.7.10-2.1.0a.jar
		* Thaumcraft|API (4.2.2.0) from tardismod-1.7.10-0.99-207.jar
		* VoltzEngineAPI (0.3.0) from VoltzEngine-1.7.10-0.7.2b188-dev-universal.jar
		* VoltzEngineAPI|energy (0.3.0) from VoltzEngine-1.7.10-0.7.2b188-dev-universal.jar
		* VoltzEngineAPI|event (0.3.0) from VoltzEngine-1.7.10-0.7.2b188-dev-universal.jar
		* VoltzEngineAPI|explosion (0.3.0) from VoltzEngine-1.7.10-0.7.2b188-dev-universal.jar
		* VoltzEngineAPI|items (0.3.0) from VoltzEngine-1.7.10-0.7.2b188-dev-universal.jar
		* VoltzEngineAPI|recipe (0.3.0) from VoltzEngine-1.7.10-0.7.2b188-dev-universal.jar
		* VoltzEngineAPI|tile (0.3.0) from VoltzEngine-1.7.10-0.7.2b188-dev-universal.jar
		* WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:OFF, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: 1.7.10-Forge10.13.4.1558-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 560 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 353.62, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by chylex** [comment]
Read.
