### ISSUE TITLE
[INVALID] Crash on load - chylex.hee.mechanics.orb.OrbAcquirableItems.initialize

### ISSUE THREAD

**Issue by ProsperCraft** [chylex/Hardcore-Ender-Expansion#18]
When trying to load the client I get this crash.

Forge .1079

---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 5/13/14 4:39 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
    at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:214)
    at chylex.hee.mechanics.orb.OrbAcquirableItems.initialize(OrbAcquirableItems.java:55)
    at chylex.hee.HardcoreEnderExpansion.onInit(HardcoreEnderExpansion.java:303)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:687)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:527)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:815)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:214)
    at org.multimc.EntryPoint.listen(EntryPoint.java:165)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:214)
    at chylex.hee.mechanics.orb.OrbAcquirableItems.initialize(OrbAcquirableItems.java:55)
    at chylex.hee.HardcoreEnderExpansion.onInit(HardcoreEnderExpansion.java:303)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:687)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:527)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:815)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:214)
    at org.multimc.EntryPoint.listen(EntryPoint.java:165)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_55, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 2001946536 bytes (1909 MB) / 3024093184 bytes (2884 MB) up to 3024093184 bytes (2884 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms3072m -Xmx3072m -XX:PermSize=256m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.03 FML v7.2.194.1079 Minecraft Forge 10.12.1.1079 109 mods loaded, 109 mods active
    mcp{9.03} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FML{7.2.194.1079} [Forge Mod Loader](forge-1.7.2-10.12.1.1079.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Forge{10.12.1.1079} [Minecraft Forge](forge-1.7.2-10.12.1.1079.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AppliedEnergistics2-Core{rv0-alpha-116} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Aroma1997Core{1.0.2.1} [Aroma1997Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CodeChickenCore{1.0.0} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NotEnoughItems{1.0.1} [Not Enough Items](NotEnoughItems-1.7.2-1.0.1-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    OpenEye{0.4} [OpenEye](OpenEye-0.4-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TConstruct-Preloader{0.1.1} [Tinkers Corestruct](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FamiliarsAPI{1.7.2c} [Familiars API](FamiliarsAPI-1.7.2c.jar) Unloaded->Constructed->Pre-initialized->Initialized
    battlegear2{1.0.5.4} [Mine & Blade Battlegear 2 - Bullseye](1.7.2-MB_Battlegear2-Bullseye-1.0.5.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
    lucky{5.0.0} [Lucky Block]([1-7-2]_Lucky_Block_v5-0-0 %281%29.jar) Unloaded->Constructed->Pre-initialized->Initialized
    bspkrsCore{6.8(1.7.2)} [bspkrsCore]([1.7.2]bspkrsCore-universal-6.8%281.7.2%29.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ArmorStatusHUD{1.25(1.7.2)} [ArmorStatusHUD]([1.7.2]ArmorStatusHUD-client-1.25%281.7.2%29.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DamageIndicatorsMod{3.1.1} [Damage Indicators]([1.7.2]DamageIndicatorsMod-3.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FloatingRuins{1.7.2.r04} [FloatingRuins]([1.7.2]FloatingRuins-universal-1.7.2.r04.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TreeCapitator{1.7.2.r02} [TreeCapitator]([1.7.2]TreeCapitator-universal-1.7.2.r02.jar) Unloaded->Constructed->Pre-initialized->Initialized
    tnfultimatetoolsforge{1.12.1.0} [Ultimate Tools]([1.7.2]UltimateTools - Universal by Umbrere[1.12.1.0].jar) Unloaded->Constructed->Pre-initialized->Initialized
    IC2{2.1.477-experimental} [IndustrialCraft 2](industrialcraft-2-2.1.477-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized
    advancedgenetics{1.5.2} [Advanced Genetics](advancedgenetics-1.5.2-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AdvancedMachines{1.0.8} [IC2 Advanced Machines Addon](AdvancedMachinesAS-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    animalbikes{1.7.2} [Animal Bikes](AnimalBikes_1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AnimationAPI{1.2.1} [AnimationAPI](AnimationAPI-1.7.2-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    antiqueatlas{4.0.1a-1.7.2} [Antique Atlas](antiqueatlas-4.0.1a-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    EnderIO{1.1.0_alpha} [Ender IO](enderio-1.1.0_alpha.56.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Mantle{1.7.2-132.45b0b50} [Mantle](Mantle-1.7.2-0.2.8.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Waila{1.5.2_1.7.2} [Waila](Waila-1.5.2a_1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TConstruct{1.7.2-1.6.0.jenkins478} [Tinkers' Construct](TConstruct-1.7.2-1.6.0.a14.jar) Unloaded->Constructed->Pre-initialized->Initialized
    aobd{1.4.1} [Another One Bites The Dust](AOBD-1.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    appliedenergistics2{rv0-alpha-116} [Applied Energistics 2](appliedenergistics2-rv0-alpha-116.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ArchimedesShips{1.7.2 v1.5.2} [Archimedes' Ships](ArchimedesShips.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Aroma1997CoreHelper{1.0.2.1} [Aroma1997Core|Helper](Aroma1997Core-1.7.2-1.0.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AromaBackup{0.0.0.2} [AromaBackup](AromaBackup-1.7.2-0.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BattleTowers{1.4.6} [Battle Towers](BattleTowers-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BetterChests{1.1.0.4} [BetterChests](BetterChests-1.7.2-1.1.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiblioCraft{1.7.0} [BiblioCraft](BiblioCraft[1.7.0][MC1.7.2].jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiomesOPlenty{2.0.0} [Biomes O' Plenty](BiomesOPlenty-1.7.2-2.0.0.773-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AWWayofTime{v1.0.1d} [Blood Magic: Alchemical Wizardry](Blood Magic-v1.0.1d.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Botania{beta-30} [Botania](Botania beta-30.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CarpentersBlocks{3.1.4} [Carpenter's Blocks](Carpenter's Blocks v3.1.4 - MC 1.7+.zip) Unloaded->Constructed->Pre-initialized->Initialized
    chisel{1.5.4b} [Chisel](Chisel-1.7.2-1.5.4b.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CustomSpawner{3.2.0.dev.R1} [DrZhark's CustomSpawner](CustomMobSpawner 3.2.0-DEV-R2.zip) Unloaded->Constructed->Pre-initialized->Initialized
    DLDungeonsJBG{1.2.10} [Doomlike Dungeons](DoomlikeDungeons-1.2.10-MC1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MoCreatures{6.2.0.dev.R1} [DrZhark's Mo'Creatures Mod](DrZharks MoCreatures Mod v6.2.0-DEV-R2.zip) Unloaded->Constructed->Pre-initialized->Initialized
    DynamicLights{1.3.3} [Dynamic Lights](DynamicLights-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module](DynamicLights-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module](DynamicLights-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DynamicLights_dropItems{1.0.7} [Dynamic Lights EntityItem Module](DynamicLights-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module](DynamicLights-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DynamicLights_mobEquipment{1.0.5} [Dynamic Lights Mob Equipment Light Module](DynamicLights-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module](DynamicLights-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DynamicLights_floodLights{1.0.1} [Dynamic Lights Flood Light](DynamicLights-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DynamicLights_otherPlayers{1.0.7} [Dynamic Lights OtherPlayers Light Module](DynamicLights-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DynamicLights_thePlayer{1.1.2} [Dynamic Lights Player Light Module](DynamicLights-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    eplus{1.7.2-2.0.1.6} [Enchanting Plus](EnchantingPlus-1.7.2-2.0.1.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Enchiridion{1.0a} [Enchiridion](Enchiridion-1.7.2-1.0b.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ExtraUtilities{1.1.0-prerelease-3} [Extra Utilities](extrautilities-1.1.0-prerelease-3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FamiliarsDefaultMobPack{1.7.2b} [DefaultMobPack](FamiliarsDefaultMobPack-1.7.2b.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FamiliarsExtendedFamPack{1.7.2b} [ExtendedFamPack](FamiliarsExtendedFamPack-1.7.2b.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FamiliarsHerobrineFamPack{1.7.2b} [HerobrineFamPack](FamiliarsHerobrineFamPack-1.7.2b.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Forestry{2.4.1.22} [Forestry for Minecraft](forestry_1.7.2-2.4.1.22.jar) Unloaded->Constructed->Pre-initialized->Initialized
    geoactivity{1.5} [GeoActivity](geoactivity-1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
    HardcoreEnderExpansion{1.5a} [Hardcore Ender Expansion](HardcoreEnderExpansion.jar) Unloaded->Constructed->Pre-initialized->Errored
    HopperDuctMod{1.3} [Hopper Ducts](hopperductmod-1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    InfernalMobs{1.5.1} [Infernal Mobs](InfernalMobs-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    inventorytweaks{1.57-116} [Inventory Tweaks](InventoryTweaks-1.57-116.jar) Unloaded->Constructed->Pre-initialized->Initialized
    IronChest{6.0.14.719} [Iron Chest](ironchest-1.7.2-6.0.14.719-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    JABBA{1.1.3} [Jabba](Jabba_1.1.3_1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    journeymap{3.3.2} [JourneyMap Unlimited Edition](JourneyMap3.3.2_Unlimited_MC1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    kwastibustmonsters{1.0.7a} [Kwasti Bust Monsters](KwastiBustMonsters-1.7.2-1.0.7.jar.zip) Unloaded->Constructed->Pre-initialized->Initialized
    kwastivil{1.0.7} [Kwasti Villagers](KwastiVillagersMod-1.7.2-1.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    LightBridgesAndDoors{0.1.9} [kris91268's Light Bridges and Doors](Light Bridges and Doors V 1.9.zip) Unloaded->Constructed->Pre-initialized->Initialized
    LunatriusCore{1.0.2.7} [LunatriusCore](LunatriusCore-1.7.2-1.0.2.7-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MagicYarn{1.1.3} [Magic Yarn](MagicYarn-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Baubles{1.0.0.11} [Baubles](Baubles-1.7.2-1.0.0.11.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Thaumcraft{4.1.1.12} [Thaumcraft](Thaumcraft-1.7.2-4.1.1.12.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Mariculture{b3} [Mariculture](Mariculture-1.7.2-b3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    radixcore{1.1.1} [RadixCore](RadixCore-1.1.1 MC-1.7.2.zip) Unloaded->Constructed->Pre-initialized->Initialized
    mca{4.0.3} [Minecraft Comes Alive](MCA-4.0.3_MC-1.7.2.zip) Unloaded->Constructed->Pre-initialized->Initialized
    meteors{2.12} [Falling Meteors](meteors-1.7.2-2.12.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineChess{1.3.8} [MineChess](MineChess-1.3.8.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MinesweeperMod{1.4.6} [Minesweeper Mod](Minesweeper-Mod-1.4.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MoreFurnaces{1.3.8} [More Furnaces](MoreFurnaces-1.3.8-MC1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    cfm{3.2.9.2} [§6MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.2.9.2-beta-build2%281.7.2%29.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MultiPageChest{1.3.1} [Multi Page Chest](MultiPageChest-1.3.1-MC1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    mychunkloader{172.02} [Chunkloader](mychunkloader-172.02.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NEIAddons{1.11.0.3} [NEI Addons](neiaddons-mc172-1.11.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NEIAddons|ExtraBees{1.11.0.3} [NEI Addons: Extra Bees](neiaddons-mc172-1.11.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NEIAddons|Forestry{1.11.0.3} [NEI Addons: Forestry](neiaddons-mc172-1.11.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NEIAddons|CraftingTables{1.11.0.3} [NEI Addons: Crafting Tables](neiaddons-mc172-1.11.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NetherDungeons{1.2.1} [Nether Dungeons](NetherDungeons-1.7.2-v-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    OpenComputers|Core{1.0.0} [OpenComputers (Core)](OpenComputers-MC1.7.2-1.2.9.136-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    OpenComputers{1.2.9.136} [OpenComputers](OpenComputers-MC1.7.2-1.2.9.136-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    harvestcraft{1.7.2c} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.2c.zip) Unloaded->Constructed->Pre-initialized->Initialized
    PneumaticCraft{1.1.9} [PneumaticCraft](PneumaticCraft-1.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized
    RopesPlus{1.6.1} [Ropes+](RopePlus-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Schematica{1.6.1.71} [Schematica](Schematica-1.7.2-1.6.1.71-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    thedalekmod{13.20} [DalekMod](The Dalek Mod - 1.7.2.zip) Unloaded->Constructed->Pre-initialized->Initialized
    TwilightForest{2.0.3} [The Twilight Forest](twilightforest-1.7.2-2.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    UndergroundBiomes{0.5} [Underground Biomes Constructs](UndergroundBiomesConstructs-1.7.2-0.5h.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AS_UpdateCheck{1.1.5} [AtomicStryker Update Check Mod](UpdateCheckerMod-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    taverns{2.2.1-0} [Village Taverns](VillageTaverns-2.2.1-0.23.jar) Unloaded->Constructed->Pre-initialized->Initialized
    voxelmap{1.7.2} [VoxelMap](voxelmap-1.7.2-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    warpbook{1.0.34} [Warp Book](warp-book-1.7.2-1.0.34.jar) Unloaded->Constructed->Pre-initialized->Initialized
    weaponmod{1.7.2 v1.14.2} [Balkon's WeaponMod](weaponmod-1.14.2 %281%29.jar) Unloaded->Constructed->Pre-initialized->Initialized
    witchery{0.18.3} [Witchery](witchery-1.7.2-0.18.3a1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    YALSM{2.1.3} [Yet Another Leather Smelting Mod](yalsm-2.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    JustAnotherSpawner{0.14.0} [Just Another Spawner](JustAnotherSpawner-0.14.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    AE2 Version: alpha rv0-alpha-116 for Forge 10.12.0.1024
    Launched Version: 1.7.2
    LWJGL: 2.9.0
    OpenGL: GeForce GT 620/PCIe/SSE2 GL version 4.4.0, NVIDIA Corporation
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: []
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: ~~ERROR~~ NullPointerException: null
    Anisotropic Filtering: Off (1)

**Comment by rockonninja** [comment]
Just a heads up, I believe the culprit is Forestry 3.6.3
