### ISSUE TITLE
1.7.10 - HEE 1.8.5 Internal Server Error Issue

### ISSUE THREAD

**Issue by Shadows-of-Fire** [chylex/Hardcore-Ender-Expansion#185]
I'm experiencing issues when on certain entries in the ender compendium.  Whenever a player hits an Enderman, this occurs for the first time, and attempts to purchase the Enderman research will also cause an ISE.  It also happened with some other entry that I couldnt test when i was flying around in The End.  [FML-Client-Latest.log](https://gist.github.com/Shadows-of-Fire/700908354d9e77ba1f1fb783060ae3a5)
Specifically, it seems to be this: 
 `[22:47:43] [Client thread/ERROR] [FML/]: Exception caught during firing event cpw.mods.fml.common.network.FMLNetworkEvent$ClientCustomPacketEvent@4c7c43c0:
java.lang.NullPointerException
	at chylex.hee.mechanics.compendium.player.PlayerDiscoveryList.loadFromNBTList(PlayerDiscoveryList.java:36) ~[PlayerDiscoveryList.class:?]
	at chylex.hee.mechanics.compendium.player.PlayerCompendiumData.loadNBTData(PlayerCompendiumData.java:188) ~[PlayerCompendiumData.class:?]
	at chylex.hee.mechanics.compendium.player.PlayerCompendiumData.<init>(PlayerCompendiumData.java:45) ~[PlayerCompendiumData.class:?]
	at chylex.hee.packets.client.C19CompendiumData.read(C19CompendiumData.java:52) ~[C19CompendiumData.class:?]
	at chylex.hee.packets.PacketPipeline.readPacket(PacketPipeline.java:126) ~[PacketPipeline.class:?]
	at chylex.hee.packets.PacketPipeline.onClientPacketReceived(PacketPipeline.java:151) ~[PacketPipeline.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_898_PacketPipeline_onClientPacketReceived_ClientCustomPacketEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103) [FMLEventChannel.class:?]
	at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30) [NetworkEventFiringHandler.class:?]
	at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18) [NetworkEventFiringHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[22:47:43] [Client thread/ERROR] [FML/]: Index: 1 Listeners:
[22:47:43] [Client thread/ERROR] [FML/]: 0: NORMAL
[22:47:43] [Client thread/ERROR] [FML/]: 1: ASM: chylex.hee.packets.PacketPipeline@493cc03a onClientPacketReceived(Lcpw/mods/fml/common/network/FMLNetworkEvent$ClientCustomPacketEvent;)V
[22:47:43] [Client thread/ERROR] [FML/]: NetworkEventFiringHandler exception
java.lang.NullPointerException
	at chylex.hee.mechanics.compendium.player.PlayerDiscoveryList.loadFromNBTList(PlayerDiscoveryList.java:36) ~[PlayerDiscoveryList.class:?]
	at chylex.hee.mechanics.compendium.player.PlayerCompendiumData.loadNBTData(PlayerCompendiumData.java:188) ~[PlayerCompendiumData.class:?]
	at chylex.hee.mechanics.compendium.player.PlayerCompendiumData.<init>(PlayerCompendiumData.java:45) ~[PlayerCompendiumData.class:?]
	at chylex.hee.packets.client.C19CompendiumData.read(C19CompendiumData.java:52) ~[C19CompendiumData.class:?]
	at chylex.hee.packets.PacketPipeline.readPacket(PacketPipeline.java:126) ~[PacketPipeline.class:?]
	at chylex.hee.packets.PacketPipeline.onClientPacketReceived(PacketPipeline.java:151) ~[PacketPipeline.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_898_PacketPipeline_onClientPacketReceived_ClientCustomPacketEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103) ~[FMLEventChannel.class:?]
	at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30) ~[NetworkEventFiringHandler.class:?]
	at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18) ~[NetworkEventFiringHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[22:47:43] [Client thread/ERROR] [FML/]: There was a critical exception handling a packet on channel hee
java.lang.NullPointerException
	at chylex.hee.mechanics.compendium.player.PlayerDiscoveryList.loadFromNBTList(PlayerDiscoveryList.java:36) ~[PlayerDiscoveryList.class:?]
	at chylex.hee.mechanics.compendium.player.PlayerCompendiumData.loadNBTData(PlayerCompendiumData.java:188) ~[PlayerCompendiumData.class:?]
	at chylex.hee.mechanics.compendium.player.PlayerCompendiumData.<init>(PlayerCompendiumData.java:45) ~[PlayerCompendiumData.class:?]
	at chylex.hee.packets.client.C19CompendiumData.read(C19CompendiumData.java:52) ~[C19CompendiumData.class:?]
	at chylex.hee.packets.PacketPipeline.readPacket(PacketPipeline.java:126) ~[PacketPipeline.class:?]
	at chylex.hee.packets.PacketPipeline.onClientPacketReceived(PacketPipeline.java:151) ~[PacketPipeline.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_898_PacketPipeline_onClientPacketReceived_ClientCustomPacketEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103) ~[FMLEventChannel.class:?]
	at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30) ~[NetworkEventFiringHandler.class:?]
	at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18) ~[NetworkEventFiringHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]`
This does not crash a server, so it is not a high-priority issue, but an inconvenience that I can't seem to source.

**Comment by chylex** [comment]
Do you have any other mod that modifies Endermen? Please post the _hee/compendium.nbt_ file.

**Comment by Shadows-of-Fire** [comment]
LegacyCraft might be modifying Endermen. I don't think anything else would be.  
I cannot seem to find that file. The only folder named hee is in the world directory and it doesn't contain it.

**Comment by chylex** [comment]
Hmm... does it happen in singleplayer? If so, could you try removing LegacyCraft, plus any other suspicious mods that could cause the issue, and try if the issue keeps happening?

**Comment by Shadows-of-Fire** [comment]
It seems to be related to LegacyCraft's overrides on the endermen.  Disabling Mob Overrides for them allows the entry to act normally.

**Comment by chylex** [comment]
Ok. Since mob overrides from other mods are not supported, I'm closing the issue - in HEE 2, this would trigger an integrity mismatch that prevents the game from running and reports which mod is overriding the mob.

I might look into porting it back to HEE 1, but people seem to be moving to 1.9 now which won't have an official update of HEE 1, so it's not a common issue.
